// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intangible.proto

/*
Package intangible is a generated protocol buffer package.

It is generated from these files:
	intangible.proto

It has these top-level messages:
	Vector
	Source
	Rendering
	API
	WavefrontOBJ
	UnitGeometry
	ClientUpdate
	PhotonVoiceChannel
	ServerUpdate
*/
package intangible

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnitGeometry_Form int32

const (
	UnitGeometry_CUBE     UnitGeometry_Form = 0
	UnitGeometry_CYLINDER UnitGeometry_Form = 1
	UnitGeometry_SPHERE   UnitGeometry_Form = 2
)

var UnitGeometry_Form_name = map[int32]string{
	0: "CUBE",
	1: "CYLINDER",
	2: "SPHERE",
}
var UnitGeometry_Form_value = map[string]int32{
	"CUBE":     0,
	"CYLINDER": 1,
	"SPHERE":   2,
}

func (x UnitGeometry_Form) String() string {
	return proto.EnumName(UnitGeometry_Form_name, int32(x))
}
func (UnitGeometry_Form) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type Vector struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vector) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Source struct {
	// uri can be any web-retrievable URL, or a primitive under the "unit" schema, such as "unit:cube" or "unit:sphere". If archive is set, uri can be a relative path within the object that archive references.
	Uri     string  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Archive *Source `protobuf:"bytes,2,opt,name=archive" json:"archive,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Source) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Source) GetArchive() *Source {
	if m != nil {
		return m.Archive
	}
	return nil
}

type Rendering struct {
	Obj  *WavefrontOBJ `protobuf:"bytes,4,opt,name=obj" json:"obj,omitempty"`
	Unit *UnitGeometry `protobuf:"bytes,5,opt,name=unit" json:"unit,omitempty"`
}

func (m *Rendering) Reset()                    { *m = Rendering{} }
func (m *Rendering) String() string            { return proto.CompactTextString(m) }
func (*Rendering) ProtoMessage()               {}
func (*Rendering) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rendering) GetObj() *WavefrontOBJ {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *Rendering) GetUnit() *UnitGeometry {
	if m != nil {
		return m.Unit
	}
	return nil
}

type API struct {
	// if endpoint is ws://, treat as connection to another server.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	// TODO(dichro): standardized API IDs, to readily identify operations like transfer to another room, moving self/other, pick up/drop objects, etc.
	Name              string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description       string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	AvroRequestSchema string `protobuf:"bytes,4,opt,name=avro_request_schema,json=avroRequestSchema" json:"avro_request_schema,omitempty"`
}

func (m *API) Reset()                    { *m = API{} }
func (m *API) String() string            { return proto.CompactTextString(m) }
func (*API) ProtoMessage()               {}
func (*API) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *API) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *API) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *API) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *API) GetAvroRequestSchema() string {
	if m != nil {
		return m.AvroRequestSchema
	}
	return ""
}

type WavefrontOBJ struct {
	// obj is a Wavefront .OBJ mesh file.
	Obj *Source `protobuf:"bytes,1,opt,name=obj" json:"obj,omitempty"`
	// mtls lists material files referenced by obj.
	Mtls map[string]*Source `protobuf:"bytes,2,rep,name=mtls" json:"mtls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// maps lists texture files referenced by obj.
	Maps map[string]*Source `protobuf:"bytes,3,rep,name=maps" json:"maps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WavefrontOBJ) Reset()                    { *m = WavefrontOBJ{} }
func (m *WavefrontOBJ) String() string            { return proto.CompactTextString(m) }
func (*WavefrontOBJ) ProtoMessage()               {}
func (*WavefrontOBJ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WavefrontOBJ) GetObj() *Source {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *WavefrontOBJ) GetMtls() map[string]*Source {
	if m != nil {
		return m.Mtls
	}
	return nil
}

func (m *WavefrontOBJ) GetMaps() map[string]*Source {
	if m != nil {
		return m.Maps
	}
	return nil
}

type UnitGeometry struct {
	Form    UnitGeometry_Form `protobuf:"varint,1,opt,name=form,enum=intangible.UnitGeometry_Form" json:"form,omitempty"`
	Rescale *Vector           `protobuf:"bytes,2,opt,name=rescale" json:"rescale,omitempty"`
}

func (m *UnitGeometry) Reset()                    { *m = UnitGeometry{} }
func (m *UnitGeometry) String() string            { return proto.CompactTextString(m) }
func (*UnitGeometry) ProtoMessage()               {}
func (*UnitGeometry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UnitGeometry) GetForm() UnitGeometry_Form {
	if m != nil {
		return m.Form
	}
	return UnitGeometry_CUBE
}

func (m *UnitGeometry) GetRescale() *Vector {
	if m != nil {
		return m.Rescale
	}
	return nil
}

// Streamed from client to server. Compatible with old Object type.
type ClientUpdate struct {
	Position *Vector `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Rotation *Vector `protobuf:"bytes,4,opt,name=rotation" json:"rotation,omitempty"`
	// TODO(dichro): these should move to a registration RPC in future; this message would then just be a Pose.
	Rendering *Rendering `protobuf:"bytes,3,opt,name=rendering" json:"rendering,omitempty"`
	Api       []*API     `protobuf:"bytes,7,rep,name=api" json:"api,omitempty"`
}

func (m *ClientUpdate) Reset()                    { *m = ClientUpdate{} }
func (m *ClientUpdate) String() string            { return proto.CompactTextString(m) }
func (*ClientUpdate) ProtoMessage()               {}
func (*ClientUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientUpdate) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ClientUpdate) GetRotation() *Vector {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *ClientUpdate) GetRendering() *Rendering {
	if m != nil {
		return m.Rendering
	}
	return nil
}

func (m *ClientUpdate) GetApi() []*API {
	if m != nil {
		return m.Api
	}
	return nil
}

type PhotonVoiceChannel struct {
	AppId      string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppVersion string `protobuf:"bytes,2,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	VoiceAppId string `protobuf:"bytes,3,opt,name=voice_app_id,json=voiceAppId" json:"voice_app_id,omitempty"`
	RoomName   string `protobuf:"bytes,4,opt,name=room_name,json=roomName" json:"room_name,omitempty"`
}

func (m *PhotonVoiceChannel) Reset()                    { *m = PhotonVoiceChannel{} }
func (m *PhotonVoiceChannel) String() string            { return proto.CompactTextString(m) }
func (*PhotonVoiceChannel) ProtoMessage()               {}
func (*PhotonVoiceChannel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PhotonVoiceChannel) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PhotonVoiceChannel) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *PhotonVoiceChannel) GetVoiceAppId() string {
	if m != nil {
		return m.VoiceAppId
	}
	return ""
}

func (m *PhotonVoiceChannel) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

// Streamed from server to client. Compatible with old Object type.
type ServerUpdate struct {
	// these describe an object
	Id          string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Position    *Vector    `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Rendering   *Rendering `protobuf:"bytes,3,opt,name=rendering" json:"rendering,omitempty"`
	Rotation    *Vector    `protobuf:"bytes,4,opt,name=rotation" json:"rotation,omitempty"`
	BoundingBox *Vector    `protobuf:"bytes,5,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
	Removed     bool       `protobuf:"varint,6,opt,name=removed" json:"removed,omitempty"`
	Api         []*API     `protobuf:"bytes,7,rep,name=api" json:"api,omitempty"`
	Rescale     *Vector    `protobuf:"bytes,9,opt,name=rescale" json:"rescale,omitempty"`
	// non-object-related updates
	VoiceChat *PhotonVoiceChannel `protobuf:"bytes,8,opt,name=voice_chat,json=voiceChat" json:"voice_chat,omitempty"`
}

func (m *ServerUpdate) Reset()                    { *m = ServerUpdate{} }
func (m *ServerUpdate) String() string            { return proto.CompactTextString(m) }
func (*ServerUpdate) ProtoMessage()               {}
func (*ServerUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ServerUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerUpdate) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ServerUpdate) GetRendering() *Rendering {
	if m != nil {
		return m.Rendering
	}
	return nil
}

func (m *ServerUpdate) GetRotation() *Vector {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *ServerUpdate) GetBoundingBox() *Vector {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *ServerUpdate) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *ServerUpdate) GetApi() []*API {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *ServerUpdate) GetRescale() *Vector {
	if m != nil {
		return m.Rescale
	}
	return nil
}

func (m *ServerUpdate) GetVoiceChat() *PhotonVoiceChannel {
	if m != nil {
		return m.VoiceChat
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "intangible.Vector")
	proto.RegisterType((*Source)(nil), "intangible.Source")
	proto.RegisterType((*Rendering)(nil), "intangible.Rendering")
	proto.RegisterType((*API)(nil), "intangible.API")
	proto.RegisterType((*WavefrontOBJ)(nil), "intangible.WavefrontOBJ")
	proto.RegisterType((*UnitGeometry)(nil), "intangible.UnitGeometry")
	proto.RegisterType((*ClientUpdate)(nil), "intangible.ClientUpdate")
	proto.RegisterType((*PhotonVoiceChannel)(nil), "intangible.PhotonVoiceChannel")
	proto.RegisterType((*ServerUpdate)(nil), "intangible.ServerUpdate")
	proto.RegisterEnum("intangible.UnitGeometry_Form", UnitGeometry_Form_name, UnitGeometry_Form_value)
}

func init() { proto.RegisterFile("intangible.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x2d, 0x3f, 0x2c, 0x93, 0x23, 0xc2, 0x55, 0xb7, 0x30, 0x40, 0xb8, 0x68, 0xab, 0x12, 0x3d,
	0x08, 0x86, 0x21, 0xa0, 0x32, 0x5a, 0x14, 0x01, 0x72, 0xb0, 0x15, 0x25, 0x96, 0x93, 0x38, 0xc2,
	0x0a, 0x76, 0x90, 0x93, 0xb0, 0x22, 0xd7, 0xd6, 0xc6, 0xe2, 0x2e, 0xb3, 0x5c, 0x11, 0x92, 0x4f,
	0xb9, 0xe5, 0x90, 0x6b, 0x6e, 0xf9, 0x2f, 0x39, 0xe6, 0x77, 0x05, 0x5c, 0x8a, 0x32, 0x01, 0x5b,
	0x71, 0x9c, 0xdc, 0x76, 0x66, 0xdf, 0x9b, 0xd5, 0xbc, 0x79, 0x23, 0x42, 0x83, 0x71, 0x45, 0xf8,
	0x05, 0x1b, 0x4f, 0x69, 0x3b, 0x91, 0x42, 0x09, 0x04, 0xd7, 0x99, 0xa0, 0x03, 0xb5, 0x33, 0x1a,
	0x2a, 0x21, 0x91, 0x07, 0xc6, 0xdc, 0x37, 0x9a, 0x46, 0xcb, 0xc4, 0xc6, 0x3c, 0x8f, 0x16, 0xbe,
	0x59, 0x44, 0x8b, 0x3c, 0xba, 0xf2, 0xad, 0x22, 0xba, 0x0a, 0x8e, 0xa0, 0x36, 0x14, 0x33, 0x19,
	0x52, 0xd4, 0x00, 0x6b, 0x26, 0x99, 0x66, 0xb9, 0x38, 0x3f, 0xa2, 0x3d, 0xd8, 0x24, 0x32, 0x9c,
	0xb0, 0x8c, 0x6a, 0x76, 0xbd, 0x83, 0xda, 0x95, 0xf7, 0x0b, 0x1a, 0x2e, 0x21, 0xc1, 0x5b, 0x03,
	0x5c, 0x4c, 0x79, 0x44, 0x25, 0xe3, 0x17, 0x68, 0x17, 0x2c, 0x31, 0x7e, 0xed, 0xdb, 0x9a, 0xe7,
	0x57, 0x79, 0x2f, 0x49, 0x46, 0xcf, 0xa5, 0xe0, 0xea, 0xc5, 0xe1, 0x31, 0xce, 0x41, 0x68, 0x0f,
	0xec, 0x19, 0x67, 0xca, 0xdf, 0xb8, 0x09, 0x3e, 0xe5, 0x4c, 0x3d, 0xa1, 0x22, 0xa6, 0x4a, 0x2e,
	0xb0, 0x46, 0x1d, 0xdb, 0x8e, 0xd9, 0xb0, 0x8e, 0x6d, 0xc7, 0x6a, 0xd8, 0xd8, 0x8e, 0x69, 0x3a,
	0xc1, 0x9b, 0x8a, 0xce, 0xd5, 0x4c, 0xd2, 0xe0, 0x9d, 0x01, 0xd6, 0xc1, 0xa0, 0x8f, 0x76, 0xc0,
	0xa1, 0x3c, 0x4a, 0x04, 0xe3, 0x6a, 0xd9, 0xcf, 0x2a, 0x46, 0x08, 0x6c, 0x4e, 0xe2, 0xa2, 0x23,
	0x17, 0xeb, 0x33, 0x6a, 0x42, 0x3d, 0xa2, 0x69, 0x28, 0x59, 0xa2, 0x98, 0xe0, 0x5a, 0x1c, 0x17,
	0x57, 0x53, 0xa8, 0x0d, 0xbf, 0x92, 0x4c, 0x8a, 0x91, 0xa4, 0x6f, 0x66, 0x34, 0x55, 0xa3, 0x34,
	0x9c, 0xd0, 0x98, 0xe8, 0xf6, 0x5c, 0xfc, 0x4b, 0x7e, 0x85, 0x8b, 0x9b, 0xa1, 0xbe, 0x08, 0x3e,
	0x99, 0xe0, 0x55, 0x1b, 0x45, 0x7f, 0x17, 0x7a, 0x18, 0x6b, 0x75, 0xd4, 0x4a, 0xfc, 0x07, 0x76,
	0xac, 0xa6, 0xa9, 0x6f, 0x36, 0xad, 0x56, 0xbd, 0x13, 0xac, 0x93, 0xad, 0xfd, 0x5c, 0x4d, 0xd3,
	0x1e, 0xd7, 0x9a, 0xe4, 0x78, 0xcd, 0x23, 0x49, 0xea, 0x5b, 0x77, 0xf1, 0x48, 0xb2, 0xe2, 0x91,
	0x24, 0xdd, 0x79, 0x0a, 0xee, 0xaa, 0x54, 0x6e, 0x80, 0x4b, 0xba, 0x28, 0x0d, 0x70, 0x49, 0x17,
	0xa8, 0x05, 0x1b, 0x19, 0x99, 0xce, 0xbe, 0x36, 0xfe, 0x02, 0xf0, 0xc0, 0xfc, 0xdf, 0xd0, 0xc5,
	0xca, 0xfa, 0x3f, 0x5a, 0x2c, 0xf8, 0x68, 0x80, 0x57, 0x1d, 0x3e, 0xfa, 0x07, 0xec, 0x73, 0x21,
	0x63, 0x5d, 0x71, 0xab, 0xf3, 0xfb, 0x3a, 0x93, 0xb4, 0x1f, 0x0b, 0x19, 0x63, 0x0d, 0xcd, 0xfd,
	0x2b, 0x69, 0x1a, 0x92, 0xe9, 0xad, 0x6f, 0x16, 0xab, 0x82, 0x4b, 0x48, 0xb0, 0x0b, 0x76, 0xce,
	0x45, 0x0e, 0xd8, 0xdd, 0xd3, 0xc3, 0x5e, 0xe3, 0x27, 0xe4, 0x81, 0xd3, 0x7d, 0xf5, 0xac, 0x7f,
	0xf2, 0xa8, 0x87, 0x1b, 0x06, 0x02, 0xa8, 0x0d, 0x07, 0x47, 0x3d, 0xdc, 0x6b, 0x98, 0xc1, 0x67,
	0x03, 0xbc, 0xee, 0x94, 0x51, 0xae, 0x4e, 0x93, 0x88, 0x28, 0x8a, 0xda, 0xe0, 0x24, 0x22, 0x65,
	0xda, 0x3e, 0xeb, 0xdf, 0x5a, 0x61, 0x72, 0xbc, 0x14, 0x8a, 0x68, 0xbc, 0xbd, 0x1e, 0x5f, 0x62,
	0xd0, 0x3e, 0xb8, 0xb2, 0xdc, 0x2d, 0xed, 0xcf, 0x7a, 0x67, 0xbb, 0x4a, 0x58, 0x2d, 0x1e, 0xbe,
	0xc6, 0xa1, 0xbf, 0xc0, 0x22, 0x09, 0xf3, 0x37, 0xb5, 0x29, 0x7e, 0xae, 0xc2, 0x0f, 0x06, 0x7d,
	0x9c, 0xdf, 0x05, 0xef, 0x0d, 0x40, 0x83, 0x89, 0x50, 0x82, 0x9f, 0x09, 0x16, 0xd2, 0xee, 0x84,
	0x70, 0x4e, 0xa7, 0x68, 0x1b, 0x6a, 0x24, 0x49, 0x46, 0x2c, 0x5a, 0x0e, 0x70, 0x83, 0x24, 0x49,
	0x3f, 0x42, 0x7f, 0x42, 0x3d, 0x4f, 0x67, 0x54, 0xa6, 0x65, 0xa3, 0x2e, 0x06, 0x92, 0x24, 0x67,
	0x45, 0x06, 0x35, 0xc1, 0xcb, 0xf2, 0x3a, 0xa3, 0x25, 0xbb, 0xd8, 0x24, 0xd0, 0xb9, 0x03, 0x5d,
	0xe2, 0x37, 0x70, 0xa5, 0x10, 0xf1, 0x48, 0xef, 0x60, 0xb1, 0x3e, 0x4e, 0x9e, 0x38, 0x21, 0x31,
	0x0d, 0x3e, 0x58, 0xe0, 0x0d, 0xa9, 0xcc, 0xa8, 0x5c, 0xca, 0xba, 0x05, 0xe6, 0xea, 0x37, 0x98,
	0x2c, 0xba, 0xb7, 0xcc, 0xdf, 0x25, 0xdb, 0x7d, 0x67, 0xf3, 0x2f, 0x78, 0x63, 0x31, 0xe3, 0x11,
	0xe3, 0x17, 0xa3, 0xb1, 0x98, 0x2f, 0xff, 0xc6, 0x6e, 0xe3, 0xd4, 0x4b, 0xdc, 0xa1, 0x98, 0x23,
	0x3f, 0x77, 0x67, 0x2c, 0x32, 0x1a, 0xf9, 0xb5, 0xa6, 0xd1, 0x72, 0x70, 0x19, 0x7e, 0xc3, 0xdc,
	0xaa, 0xd6, 0x76, 0xef, 0xb4, 0x36, 0x7a, 0x08, 0xc5, 0x08, 0x46, 0xe1, 0x84, 0x28, 0xdf, 0xd1,
	0x84, 0x3f, 0xaa, 0x84, 0x9b, 0x16, 0xc0, 0x6e, 0xb6, 0x8c, 0xd4, 0xb8, 0xa6, 0x3f, 0x35, 0xfb,
	0x5f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x11, 0x98, 0x31, 0xff, 0x7e, 0x06, 0x00, 0x00,
}
