// Code generated by protoc-gen-go.
// source: intangible.proto
// DO NOT EDIT!

/*
Package Intangible is a generated protocol buffer package.

It is generated from these files:
	intangible.proto

It has these top-level messages:
	Vector
	Source
	Mesh
	Texture
	Rendering
	API
	Object
	WavefrontOBJ
*/
package Intangible

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Source struct {
	// uri can be any web-retrievable URL, or a primitive under the "unit" schema, such as "unit:cube" or "unit:sphere". If archive is set, uri can be a relative path within the object that archive references.
	Uri     string  `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Archive *Source `protobuf:"bytes,2,opt,name=archive" json:"archive,omitempty"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Source) GetArchive() *Source {
	if m != nil {
		return m.Archive
	}
	return nil
}

type Mesh struct {
	Source   *Source `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Rescale  *Vector `protobuf:"bytes,2,opt,name=rescale" json:"rescale,omitempty"`
	Rotation *Vector `protobuf:"bytes,3,opt,name=rotation" json:"rotation,omitempty"`
}

func (m *Mesh) Reset()                    { *m = Mesh{} }
func (m *Mesh) String() string            { return proto.CompactTextString(m) }
func (*Mesh) ProtoMessage()               {}
func (*Mesh) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Mesh) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Mesh) GetRescale() *Vector {
	if m != nil {
		return m.Rescale
	}
	return nil
}

func (m *Mesh) GetRotation() *Vector {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Texture struct {
	Source *Source `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *Texture) Reset()                    { *m = Texture{} }
func (m *Texture) String() string            { return proto.CompactTextString(m) }
func (*Texture) ProtoMessage()               {}
func (*Texture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Texture) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type Rendering struct {
	Mesh    *Mesh         `protobuf:"bytes,2,opt,name=mesh" json:"mesh,omitempty"`
	Texture *Texture      `protobuf:"bytes,3,opt,name=texture" json:"texture,omitempty"`
	Obj     *WavefrontOBJ `protobuf:"bytes,4,opt,name=obj" json:"obj,omitempty"`
}

func (m *Rendering) Reset()                    { *m = Rendering{} }
func (m *Rendering) String() string            { return proto.CompactTextString(m) }
func (*Rendering) ProtoMessage()               {}
func (*Rendering) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Rendering) GetMesh() *Mesh {
	if m != nil {
		return m.Mesh
	}
	return nil
}

func (m *Rendering) GetTexture() *Texture {
	if m != nil {
		return m.Texture
	}
	return nil
}

func (m *Rendering) GetObj() *WavefrontOBJ {
	if m != nil {
		return m.Obj
	}
	return nil
}

type API struct {
	// if endpoint is ws://, treat as connection to another server.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	// TODO(dichro): standardized API IDs, to readily identify operations like transfer to another room, moving self/other, pick up/drop objects, etc.
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// TODO(dichro): schema for request+reply. Avro? There appears to be no easily accessible protobuf, thrift, or json-schema IDL parser that'll work with Unity.
	AvroRequestSchema string `protobuf:"bytes,4,opt,name=avro_request_schema,json=avroRequestSchema" json:"avro_request_schema,omitempty"`
}

func (m *API) Reset()                    { *m = API{} }
func (m *API) String() string            { return proto.CompactTextString(m) }
func (*API) ProtoMessage()               {}
func (*API) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Object struct {
	Id          string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Position    *Vector    `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Rendering   *Rendering `protobuf:"bytes,3,opt,name=rendering" json:"rendering,omitempty"`
	Rotation    *Vector    `protobuf:"bytes,4,opt,name=rotation" json:"rotation,omitempty"`
	BoundingBox *Vector    `protobuf:"bytes,5,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
	Removed     bool       `protobuf:"varint,6,opt,name=removed" json:"removed,omitempty"`
	Api         []*API     `protobuf:"bytes,7,rep,name=api" json:"api,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Object) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Object) GetRendering() *Rendering {
	if m != nil {
		return m.Rendering
	}
	return nil
}

func (m *Object) GetRotation() *Vector {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Object) GetBoundingBox() *Vector {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

func (m *Object) GetApi() []*API {
	if m != nil {
		return m.Api
	}
	return nil
}

type WavefrontOBJ struct {
	// obj is a Wavefront .OBJ mesh file.
	Obj *Source `protobuf:"bytes,1,opt,name=obj" json:"obj,omitempty"`
	// mtls lists material files referenced by obj.
	Mtls map[string]*Source `protobuf:"bytes,2,rep,name=mtls" json:"mtls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// maps lists texture files referenced by obj.
	Maps map[string]*Source `protobuf:"bytes,3,rep,name=maps" json:"maps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WavefrontOBJ) Reset()                    { *m = WavefrontOBJ{} }
func (m *WavefrontOBJ) String() string            { return proto.CompactTextString(m) }
func (*WavefrontOBJ) ProtoMessage()               {}
func (*WavefrontOBJ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WavefrontOBJ) GetObj() *Source {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *WavefrontOBJ) GetMtls() map[string]*Source {
	if m != nil {
		return m.Mtls
	}
	return nil
}

func (m *WavefrontOBJ) GetMaps() map[string]*Source {
	if m != nil {
		return m.Maps
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "Intangible.Vector")
	proto.RegisterType((*Source)(nil), "Intangible.Source")
	proto.RegisterType((*Mesh)(nil), "Intangible.Mesh")
	proto.RegisterType((*Texture)(nil), "Intangible.Texture")
	proto.RegisterType((*Rendering)(nil), "Intangible.Rendering")
	proto.RegisterType((*API)(nil), "Intangible.API")
	proto.RegisterType((*Object)(nil), "Intangible.Object")
	proto.RegisterType((*WavefrontOBJ)(nil), "Intangible.WavefrontOBJ")
}

func init() { proto.RegisterFile("intangible.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x96, 0x3f, 0xea, 0xc4, 0x93, 0xe8, 0x7d, 0xc3, 0x54, 0x48, 0x56, 0x4f, 0xc1, 0xe2, 0x50,
	0x21, 0xc8, 0xa1, 0x15, 0x08, 0x71, 0xa3, 0x12, 0x82, 0x16, 0x55, 0x45, 0x5b, 0x04, 0xc7, 0x68,
	0x9d, 0x2c, 0x8d, 0x4b, 0xe2, 0x35, 0x6b, 0x3b, 0x4a, 0xfa, 0x07, 0xb8, 0xf0, 0x27, 0xe0, 0x87,
	0xf0, 0xdb, 0x98, 0x5d, 0x7f, 0xd4, 0x48, 0x31, 0x15, 0xe2, 0x36, 0xb3, 0xf3, 0x3c, 0xf3, 0xf1,
	0xcc, 0x68, 0x61, 0x14, 0x27, 0x39, 0x4f, 0xae, 0xe2, 0x68, 0x29, 0x26, 0xa9, 0x92, 0xb9, 0x44,
	0x38, 0x6d, 0x5e, 0xc2, 0x23, 0xf0, 0x3e, 0x88, 0x59, 0x2e, 0x15, 0x0e, 0xc1, 0xda, 0x04, 0xd6,
	0xd8, 0x3a, 0xb4, 0x99, 0xb5, 0xd1, 0xde, 0x36, 0xb0, 0x4b, 0x6f, 0xab, 0xbd, 0x9b, 0xc0, 0x29,
	0xbd, 0x9b, 0xf0, 0x0d, 0x78, 0x97, 0xb2, 0x50, 0x33, 0x81, 0x23, 0x70, 0x0a, 0x15, 0x1b, 0x96,
	0xcf, 0xb4, 0x89, 0x8f, 0xa1, 0xc7, 0xd5, 0x6c, 0x11, 0xaf, 0x85, 0x61, 0x0f, 0x8e, 0x70, 0x72,
	0x5b, 0x6d, 0x52, 0xd2, 0x58, 0x0d, 0x09, 0x7f, 0x58, 0xe0, 0x9e, 0x8b, 0x6c, 0x81, 0x8f, 0xc0,
	0xcb, 0x4c, 0x2c, 0x70, 0x3b, 0x59, 0x15, 0x42, 0x97, 0x50, 0x22, 0x9b, 0xf1, 0xe5, 0xce, 0x12,
	0xe5, 0x34, 0xac, 0x86, 0xe0, 0x04, 0xfa, 0x34, 0x34, 0xcf, 0x63, 0x99, 0x98, 0x09, 0x76, 0xc3,
	0x1b, 0xcc, 0x99, 0xdb, 0xb7, 0x46, 0x36, 0x83, 0xb2, 0xd6, 0x94, 0x46, 0x0a, 0x5f, 0x43, 0xef,
	0xbd, 0xd8, 0xe4, 0x85, 0x12, 0x7f, 0xd3, 0xe6, 0x8e, 0x44, 0xdf, 0x2c, 0xf0, 0x99, 0x48, 0xe6,
	0x42, 0xc5, 0xc9, 0x15, 0x3e, 0x04, 0x77, 0x45, 0xa3, 0x57, 0x33, 0x8c, 0xda, 0x99, 0xb4, 0x24,
	0xcc, 0x44, 0xf1, 0x09, 0xf4, 0xf2, 0xb2, 0x78, 0xd5, 0xfd, 0x7e, 0x1b, 0x58, 0xf5, 0xc5, 0x6a,
	0x0c, 0x35, 0xe8, 0xc8, 0xe8, 0xba, 0xea, 0x2e, 0x68, 0x43, 0x3f, 0xf2, 0xb5, 0xf8, 0xa4, 0x64,
	0x92, 0x5f, 0x9c, 0x9c, 0x31, 0x0d, 0x0a, 0xbf, 0x5a, 0xe0, 0xbc, 0x7c, 0x77, 0x8a, 0x07, 0xd0,
	0xa7, 0xa6, 0x52, 0x49, 0x77, 0x52, 0x6d, 0xb2, 0xf1, 0x11, 0xc1, 0x4d, 0xf8, 0xaa, 0x14, 0xda,
	0x67, 0xc6, 0xc6, 0x31, 0x0c, 0xe6, 0x24, 0xae, 0x8a, 0xd3, 0x46, 0x54, 0x9f, 0xb5, 0x9f, 0x48,
	0xf3, 0x7d, 0xbe, 0x56, 0x72, 0xaa, 0xc4, 0x97, 0x42, 0x64, 0xf9, 0x34, 0x9b, 0x2d, 0xc4, 0x8a,
	0x9b, 0xae, 0x7c, 0x76, 0x4f, 0x87, 0x58, 0x19, 0xb9, 0x34, 0x81, 0xf0, 0xbb, 0x0d, 0xde, 0x45,
	0x74, 0x4d, 0xab, 0xc0, 0xff, 0xc0, 0x8e, 0xe7, 0x55, 0x1b, 0x64, 0xe9, 0xf5, 0xa5, 0x32, 0x8b,
	0x4d, 0xa5, 0xee, 0x6d, 0x37, 0x18, 0x3c, 0x06, 0x5f, 0xd5, 0x12, 0x57, 0x8a, 0xdd, 0x6f, 0x13,
	0x1a, 0xfd, 0xd9, 0x2d, 0xee, 0xb7, 0x1b, 0x71, 0xef, 0xbe, 0x11, 0x7c, 0x0a, 0xc3, 0x48, 0x16,
	0xc9, 0x9c, 0xb8, 0xd3, 0x48, 0x6e, 0x82, 0xbd, 0x4e, 0xce, 0xa0, 0xc6, 0x9d, 0xc8, 0x0d, 0x06,
	0xfa, 0x70, 0x57, 0x72, 0x2d, 0xe6, 0x81, 0x47, 0x8c, 0x3e, 0xab, 0x5d, 0x7c, 0x00, 0x0e, 0x4f,
	0xe3, 0xa0, 0x37, 0x76, 0x28, 0xcf, 0xff, 0xed, 0x3c, 0xb4, 0x20, 0xa6, 0x63, 0xe1, 0x4f, 0x1b,
	0x86, 0xed, 0x1d, 0xd2, 0xfd, 0x98, 0x55, 0x5b, 0x9d, 0x87, 0xa8, 0xc3, 0xf8, 0x8c, 0xae, 0x2c,
	0x5f, 0x66, 0xa4, 0x9d, 0x4e, 0x1d, 0x76, 0x5d, 0xc4, 0xe4, 0x9c, 0x40, 0xaf, 0x92, 0x5c, 0x6d,
	0x99, 0xc1, 0x1b, 0x1e, 0x4f, 0x33, 0x92, 0xf0, 0x0e, 0x1e, 0x81, 0x6a, 0x1e, 0x99, 0x07, 0x6f,
	0xc1, 0x6f, 0x52, 0xe9, 0xef, 0xe1, 0xb3, 0xd8, 0xd6, 0xdf, 0x03, 0x99, 0x78, 0x08, 0x7b, 0x6b,
	0xbe, 0x2c, 0xfe, 0xf4, 0x39, 0x94, 0x80, 0x17, 0xf6, 0x73, 0xcb, 0x24, 0xab, 0xf3, 0xff, 0x6b,
	0xb2, 0xc8, 0x33, 0x9f, 0xdf, 0xf1, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x05, 0xfc, 0x50,
	0x10, 0x05, 0x00, 0x00,
}
